defaults:
    compile:
        input: .\docs\adr\
        plugin: archgo
    verify:
        input: .\docs\adr\
        plugin: fscheck
plugin_configs:
    arch-go:
        output-dir: .\adg\
    fscheck:
        root-dir: .
